<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cMhnip9' shared service.

return $this->privates['.service_locator.cMhnip9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'produit' => ['privates', '.errored..service_locator.cMhnip9.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.cMhnip9": it references class "App\\Entity\\Produit" but no such service exists.'],
], [
    'produit' => 'App\\Entity\\Produit',
]);
