<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.c7KQaCt' shared service.

return $this->privates['.service_locator.c7KQaCt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\GesCosController::create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController::createClient' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController::createDetail' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController::createFournisseur' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController::createProduit' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController::createType' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:create' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:createClient' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:createDetail' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:createFournisseur' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:createProduit' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\GesCosController:createType' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
], [
    'App\\Controller\\GesCosController::create' => '?',
    'App\\Controller\\GesCosController::createClient' => '?',
    'App\\Controller\\GesCosController::createDetail' => '?',
    'App\\Controller\\GesCosController::createFournisseur' => '?',
    'App\\Controller\\GesCosController::createProduit' => '?',
    'App\\Controller\\GesCosController::createType' => '?',
    'App\\Controller\\GesCosController:create' => '?',
    'App\\Controller\\GesCosController:createClient' => '?',
    'App\\Controller\\GesCosController:createDetail' => '?',
    'App\\Controller\\GesCosController:createFournisseur' => '?',
    'App\\Controller\\GesCosController:createProduit' => '?',
    'App\\Controller\\GesCosController:createType' => '?',
]);
