<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkewtDE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkewtDE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKkewtDE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKkewtDE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKkewtDE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KkewtDE',
    'container.build_id' => 'e97ad13e',
    'container.build_time' => 1575122339,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkewtDE');
