<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTsx01tq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTsx01tq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTsx01tq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTsx01tq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTsx01tq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Tsx01tq',
    'container.build_id' => 'be29a2a9',
    'container.build_time' => 1572909805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTsx01tq');
